
# Task Configuration - Single language pair
tasks:
  task_en_is:
    src_tgt: "en-is"
    node_gpu: 0:0
    enc_sharing_group: ["shared", "mixed"]
    dec_sharing_group: ["shared_low", "is"]
    transforms: [prefix]
    src_prefix: "<to_is>"
    tgt_prefix: "<is>"


src_vocab:
  en: /scratch/project_462000964/members/wangchao/training/four_nodes/tokenizer.json
tgt_vocab:
  is: /scratch/project_462000964/members/wangchao/training/four_nodes/tokenizer.json

use_hf_tokenizer: true

model: /scratch/project_462000964/members/wangchao/training/four_nodes/models/62500/ # Path to trained model
task_id: task_en_is
seed: 42
src: /scratch/project_462000964/shared/hplt_bilingual/is-en.tmx/val_en.txt
output: eval_en_is.txt

gpu: 0
batch_size: 16
batch_type: sents
beam_size: 1
max_length: 256
min_length: 1
verbose: false





