ab_fixed_length: 50
ab_layer_norm: layernorm
ab_layers: []
accum_count: '1'
accum_steps:
- 0
adagrad_accumulator_init: 0
adam_beta1: 0.9
adam_beta2: 0.999
alignment_heads: 0
alignment_layer: -3
apex_opt_level: O1
attention_dropout:
- 0.1
average_decay: 0
average_every: 1
batch_size: '4096'
batch_type: tokens
bidir_edges: true
bridge_extra_node: true
bucket_size: 2048
cnn_kernel_width: 3
config: /scratch/project_462000088/members/jrvc//amernlp23/scripts/mammoth_cfgs/cfg-base-hamburger.yml
data: '{''train_es-cni'': {''src_tgt'': ''es-cni'', ''node_gpu'': ''0:0'', ''enc_sharing_group'':
  [''es'', ''all''], ''dec_sharing_group'': [''cni'', ''all'', ''cni''], ''path_src'':
  ''/scratch/project_462000088/members/jrvc/data/train.es-cni.es'', ''path_tgt'':
  ''/scratch/project_462000088/members/jrvc/data/train.es-cni.cni'', ''transforms'':
  [''onmt_tokenize'', ''filtertoolong'']}, ''train_cni-cni'': {''src_tgt'': ''cni-cni'',
  ''node_gpu'': ''0:0'', ''enc_sharing_group'': [''cni'', ''all''], ''dec_sharing_group'':
  [''cni'', ''all'', ''cni''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-cni.cni'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-cni.cni'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'', ''bart'']}, ''train_es-aym'':
  {''src_tgt'': ''es-aym'', ''node_gpu'': ''0:0'', ''enc_sharing_group'': [''es'',
  ''all''], ''dec_sharing_group'': [''aym'', ''all'', ''aym''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-aym.es'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-aym.aym'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'']}, ''train_aym-aym'': {''src_tgt'':
  ''aym-aym'', ''node_gpu'': ''0:0'', ''enc_sharing_group'': [''aym'', ''all''], ''dec_sharing_group'':
  [''aym'', ''all'', ''aym''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-aym.aym'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-aym.aym'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'', ''bart'']}, ''train_es-tar'':
  {''src_tgt'': ''es-tar'', ''node_gpu'': ''0:0'', ''enc_sharing_group'': [''es'',
  ''all''], ''dec_sharing_group'': [''tar'', ''all'', ''tar''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-tar.es'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-tar.tar'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'']}, ''train_tar-tar'': {''src_tgt'':
  ''tar-tar'', ''node_gpu'': ''0:0'', ''enc_sharing_group'': [''tar'', ''all''], ''dec_sharing_group'':
  [''tar'', ''all'', ''tar''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-tar.tar'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-tar.tar'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'', ''bart'']}, ''train_es-bzd'':
  {''src_tgt'': ''es-bzd'', ''node_gpu'': ''0:1'', ''enc_sharing_group'': [''es'',
  ''all''], ''dec_sharing_group'': [''bzd'', ''all'', ''bzd''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-bzd.es'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-bzd.bzd'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'']}, ''train_bzd-bzd'': {''src_tgt'':
  ''bzd-bzd'', ''node_gpu'': ''0:1'', ''enc_sharing_group'': [''bzd'', ''all''], ''dec_sharing_group'':
  [''bzd'', ''all'', ''bzd''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-bzd.bzd'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-bzd.bzd'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'', ''bart'']}, ''train_es-gn'':
  {''src_tgt'': ''es-gn'', ''node_gpu'': ''0:1'', ''enc_sharing_group'': [''es'',
  ''all''], ''dec_sharing_group'': [''gn'', ''all'', ''gn''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-gn.es'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-gn.gn'', ''transforms'':
  [''onmt_tokenize'', ''filtertoolong'']}, ''train_gn-gn'': {''src_tgt'': ''gn-gn'',
  ''node_gpu'': ''0:1'', ''enc_sharing_group'': [''gn'', ''all''], ''dec_sharing_group'':
  [''gn'', ''all'', ''gn''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-gn.gn'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-gn.gn'', ''transforms'':
  [''onmt_tokenize'', ''filtertoolong'', ''bart'']}, ''train_es-shp'': {''src_tgt'':
  ''es-shp'', ''node_gpu'': ''0:1'', ''enc_sharing_group'': [''es'', ''all''], ''dec_sharing_group'':
  [''shp'', ''all'', ''shp''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-shp.es'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-shp.shp'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'']}, ''train_shp-shp'': {''src_tgt'':
  ''shp-shp'', ''node_gpu'': ''0:1'', ''enc_sharing_group'': [''shp'', ''all''], ''dec_sharing_group'':
  [''shp'', ''all'', ''shp''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-shp.shp'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-shp.shp'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'', ''bart'']}, ''train_es-en'':
  {''src_tgt'': ''es-en'', ''node_gpu'': ''0:2'', ''enc_sharing_group'': [''es'',
  ''all''], ''dec_sharing_group'': [''en'', ''all'', ''en''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-en.es'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-en.en'', ''transforms'':
  [''onmt_tokenize'', ''filtertoolong'']}, ''train_en-en'': {''src_tgt'': ''en-en'',
  ''node_gpu'': ''0:2'', ''enc_sharing_group'': [''en'', ''all''], ''dec_sharing_group'':
  [''en'', ''all'', ''en''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-en.en'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-en.en'', ''transforms'':
  [''onmt_tokenize'', ''filtertoolong'', ''bart'']}, ''train_es-oto'': {''src_tgt'':
  ''es-oto'', ''node_gpu'': ''0:2'', ''enc_sharing_group'': [''es'', ''all''], ''dec_sharing_group'':
  [''oto'', ''all'', ''oto''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-oto.es'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-oto.oto'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'']}, ''train_oto-oto'': {''src_tgt'':
  ''oto-oto'', ''node_gpu'': ''0:2'', ''enc_sharing_group'': [''oto'', ''all''], ''dec_sharing_group'':
  [''oto'', ''all'', ''oto''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-oto.oto'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-oto.oto'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'', ''bart'']}, ''train_es-hch'':
  {''src_tgt'': ''es-hch'', ''node_gpu'': ''0:2'', ''enc_sharing_group'': [''es'',
  ''all''], ''dec_sharing_group'': [''hch'', ''all'', ''hch''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-hch.es'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-hch.hch'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'']}, ''train_hch-hch'': {''src_tgt'':
  ''hch-hch'', ''node_gpu'': ''0:2'', ''enc_sharing_group'': [''hch'', ''all''], ''dec_sharing_group'':
  [''hch'', ''all'', ''hch''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-hch.hch'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-hch.hch'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'', ''bart'']}, ''train_es-nah'':
  {''src_tgt'': ''es-nah'', ''node_gpu'': ''0:3'', ''enc_sharing_group'': [''es'',
  ''all''], ''dec_sharing_group'': [''nah'', ''all'', ''nah''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-nah.es'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-nah.nah'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'']}, ''train_nah-nah'': {''src_tgt'':
  ''nah-nah'', ''node_gpu'': ''0:3'', ''enc_sharing_group'': [''nah'', ''all''], ''dec_sharing_group'':
  [''nah'', ''all'', ''nah''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-nah.nah'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-nah.nah'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'', ''bart'']}, ''train_es-quy'':
  {''src_tgt'': ''es-quy'', ''node_gpu'': ''0:3'', ''enc_sharing_group'': [''es'',
  ''all''], ''dec_sharing_group'': [''quy'', ''all'', ''quy''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-quy.es'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-quy.quy'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'']}, ''train_quy-quy'': {''src_tgt'':
  ''quy-quy'', ''node_gpu'': ''0:3'', ''enc_sharing_group'': [''quy'', ''all''], ''dec_sharing_group'':
  [''quy'', ''all'', ''quy''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-quy.quy'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-quy.quy'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'', ''bart'']}, ''train_es-czn'':
  {''src_tgt'': ''es-czn'', ''node_gpu'': ''0:3'', ''enc_sharing_group'': [''czn'',
  ''all''], ''dec_sharing_group'': [''czn'', ''all'', ''czn''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-czn.es'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-czn.czn'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'']}, ''train_czn-czn'': {''src_tgt'':
  ''czn-czn'', ''node_gpu'': ''0:0'', ''enc_sharing_group'': [''czn'', ''all''], ''dec_sharing_group'':
  [''czn'', ''all'', ''czn''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/train.es-czn.czn'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/train.es-czn.czn'',
  ''transforms'': [''onmt_tokenize'', ''filtertoolong'', ''bart'']}, ''train_es-es'':
  {''src_tgt'': ''es-es'', ''node_gpu'': ''0:3'', ''enc_sharing_group'': [''es'',
  ''all''], ''dec_sharing_group'': [''es'', ''all'', ''es''], ''path_src'': ''/scratch/project_462000088/members/jrvc/data/all-es.es'',
  ''path_tgt'': ''/scratch/project_462000088/members/jrvc/data/all-es.es'', ''transforms'':
  [''onmt_tokenize'', ''filtertoolong'', ''bart'']}}'
data_type: text
dec_layers:
- 1
- 4
- 1
dec_rnn_size: 500
decay_method: none
decay_steps: 10000
decoder_type: transformer
dropout: '0.1'
dropout_steps:
- 0
early_stopping: 0
enc_layers:
- 5
- 1
enc_rnn_size: 500
encoder_type: transformer
epochs: 0
exp: ''
exp_host: ''
feat_merge: concat
feat_vec_exponent: 0.7
feat_vec_size: -1
generator_function: softmax
global_attention: general
global_attention_function: softmax
gpu_backend: nccl
gpu_ranks:
- 0
- 1
- 2
- 3
gpu_verbose_level: 0
gpuid: []
heads: '8'
hidden_ab_size: 2048
input_feed: 1
insert_ratio: 0.0
keep_checkpoint: '-1'
label_smoothing: '0.1'
lambda_align: 0.0
lambda_coverage: 0.0
layers: -1
learning_rate: '3.0'
learning_rate_decay: 0.5
log_file: ''
log_file_level: '0'
loss_scale: 0
mask_length: subword
mask_ratio: '0.2'
master_ip: localhost
master_port: 9959
max_generator_batches: '2'
max_grad_norm: '0.0'
max_relative_positions: 0
model_dtype: fp32
model_task: seq2seq
model_type: text
n_buckets: 1024
n_edge_types: 2
n_node: 2
n_nodes: 1
n_sample: 0
n_steps: 2
node_rank: 0
normalization: tokens
optim: adafactor
overwrite: 'False'
param_init: '0.0'
param_init_glorot: 'True'
permute_sent_ratio: 0.0
poisson_lambda: 3.0
pos_ffn_activation_fn: relu
position_encoding: 'True'
queue_size: 40
random_ratio: 0.0
replace_length: '1'
report_every: '50'
reset_optim: none
reversible_tokenization: joiner
rnn_size: '512'
rnn_type: LSTM
rotate_ratio: 0.0
save_all_gpus: 'False'
save_checkpoint_steps: '50000'
save_model: /scratch/project_462000088/members/jrvc//amernlp23/models/amernlp_51-141-ae
seed: '3435'
self_attn_type: scaled-dot
skip_empty_level: silent
src_ggnn_size: 0
src_onmttok_kwargs: '{''mode'': ''none'', ''spacer_annotate'': True}'
src_seq_length: '200'
src_subword_alpha: 0
src_subword_model: /scratch/project_462000088/members/jrvc/data/all_32k.model
src_subword_nbest: 1
src_subword_type: sentencepiece
src_subword_vocab: ''
src_vocab: '{''es'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'',
  ''cni'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''aym'':
  ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''bzd'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'',
  ''gn'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''en'':
  ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''oto'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'',
  ''nah'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''quy'':
  ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''tar'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'',
  ''shp'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''hch'':
  ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''czn'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab''}'
src_vocab_size: '100000'
src_vocab_threshold: 0
src_word_vec_size: 500
src_words_min_frequency: 0
start_decay_steps: 50000
state_dim: 512
subword_alpha: '0.1'
subword_nbest: '20'
switchout_temperature: 1.0
task_distribution_strategy: weighted_sampling
tensorboard_log_dir: runs/onmt
tgt_onmttok_kwargs: '{''mode'': ''none'', ''spacer_annotate'': True}'
tgt_seq_length: '200'
tgt_subword_alpha: 0
tgt_subword_model: /scratch/project_462000088/members/jrvc/data/all_32k.model
tgt_subword_nbest: 1
tgt_subword_type: sentencepiece
tgt_subword_vocab: ''
tgt_vocab: '{''es'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'',
  ''cni'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''aym'':
  ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''bzd'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'',
  ''gn'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''en'':
  ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''oto'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'',
  ''nah'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''quy'':
  ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''tar'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'',
  ''shp'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''hch'':
  ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab'', ''czn'': ''/scratch/project_462000088/members/jrvc/data/all_32k.vocab''}'
tgt_vocab_size: '100000'
tgt_vocab_threshold: 0
tgt_word_vec_size: 500
tgt_words_min_frequency: 0
tokendrop_temperature: 1.0
tokenmask_temperature: 1.0
train_from: ''
train_steps: 250000
transformer_ff: '2048'
transforms: []
truncated_decoder: 0
valid_batch_size: '4096'
valid_steps: '1000000'
vocab_size_multiple: 1
warmup_steps: '20000'
weight_decay: '0.05'
word_vec_size: '512'
world_size: '4'
