# translation_config.yaml

model: ./models/
task_id: bart_translation
src_vocab:
  en: ./src_vocab_en.txt
tgt_vocab:
  es: ./src_vocab_en.txt
seed: 42
src: ./src.en
output: ./output.txt
batch_size: 1
batch_type: sents
shard_size: 0
model_dtype: fp32
beam_size: 1
max_length: 20
transforms: [huggingface]
src_hf_model_name: vgaraujov/bart-base-translation-en-es
tgt_hf_model_name: vgaraujov/bart-base-translation-en-es

tasks:
  bart_translation: # This should match your --task_id
    src_tgt: en-es # source-target language pair
    # Add other task-specific configurations as needed
    enc_sharing_group: ["en"] # encoder sharing group
    dec_sharing_group: ["es"] # decoder sharing group
    introduce_at_training_step: 0
    weight: 1
