tasks:
  mt_eng-spa:
    src_tgt: "eng-spa"
    weight: 1
    introduce_at_training_step: 0
    node_gpu: "0:0"
    enc_sharing_group: ["eng"]
    dec_sharing_group: ["spa"]
    transforms: [filtertoolong]
    path_src: /scratch/project_2017852/MARMoT/data/sentmt/eng-spa.eng.gz
    path_tgt: /scratch/project_2017852/MARMoT/data/sentmt/eng-spa.spa.gz
    path_valid_src: /scratch/project_2017852/MARMoT/data/flores200/dev/eng_Latn.dev
    path_valid_tgt: /scratch/project_2017852/MARMoT/data/flores200/dev/spa_Latn.dev



src_vocab:
  eng: /scratch/project_2017852/MARMoT/tokenizer/tatoeba_hplt_multisynt/eng/32000/tokenizer.json
tgt_vocab:
  spa: /scratch/project_2017852/MARMoT/tokenizer/tatoeba_hplt_multisynt/spa/32000/tokenizer.json


# Model Architecture Options
enc_layers: [6]
dec_layers: [6]

model_dim: 768      
dropout: 0.1      
model_dtype: bf16     
add_language_tokens: false

# x-transformers specific options
x_transformers_opts:
  attn_flash: true     
  rotary_pos_emb: true     
  tie_embedding: false    
  heads: 8
  pre_norm: false
  post_emb_norm: true
  attn_dropout: 0.1
  ff_dropout: 0.1
  use_abs_pos_emb: false

src_seq_length_min: 1
tgt_seq_length_min: 1
src_seq_length_max: 1024
tgt_seq_length_max: 1024
max_length: 1024

# Training Configuration
train_steps: 100000
accum_count: [20]
lookahead_minibatches: 20       
batch_size: 8192    
batch_type: tokens  
normalization: tokens  
queue_size: 120

# Optimizer settings (from create_opts)
optim: adamw

learning_rate: 0.0003
adam_beta1: 0.9
adam_beta2: 0.999
weight_decay: 0.01
max_grad_norm: 1.0
label_smoothing: 0.1

# Learning rate scheduling
warmup_steps: 10000
decay_method: linear_warmup
learning_rate_decay: 0.5     
start_decay_steps: 10000   
average_decay: 0

world_size: 1
gpu_ranks: [0]
node_rank: 0
task_distribution_strategy: weighted_sampling

seed: 42
# Decoding parameters during validation
valid_batch_size: 16      
valid_steps: 2500    
valid_timeout: 300     
valid_decode_timeout: 60      
valid_max_length: 1024
valid_metrics: [bleu]
beam_size: 1

save_checkpoint_steps: 2500    
keep_checkpoint: 1

# Logging and Monitoring

log_model_structure: false
# tensorboard: true               # enable tensorboard logging
# tensorboard_log_dir: ./logs     # tensorboard log directory
report_tflops: true
report_every: 500     
report_training_accuracy: false

# Model saving
save_model: /scratch/project_2017852/members/chao/test-runs/model/
save_strategy: best_and_last
