src_vocab:
  'all': tools/demo/configs/hydra/vocab/mammoth-hydra.64k.spm.vocab
tgt_vocab:
  'en': tools/demo/configs/hydra/vocab/mammoth-hydra.64k.spm.vocab
  'fr': tools/demo/configs/hydra/vocab/mammoth-hydra.64k.spm.vocab
  'ru': tools/demo/configs/hydra/vocab/mammoth-hydra.64k.spm.vocab

overwrite: False
tasks:
  # GPU 0:0
  defmod_en:
    src_tgt: all-en
    enc_sharing_group: [all]
    dec_sharing_group: [en1, dm, en2]
    node_gpu: 0:0
    path_src: /scratch/project_2005099/data/mammoth-hydra/codwoe/en.src.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/codwoe/en.tgt.sp
    transforms: [filtertoolong]
  pargen_en:
    src_tgt: all-en
    enc_sharing_group: [all]
    dec_sharing_group: [en1, pg, en2]
    node_gpu: 0:0
    path_src: /scratch/project_2005099/data/mammoth-hydra/tapaco/en.src.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/tapaco/en.tgt.sp
    transforms: [filtertoolong]
  texsim_en:
    src_tgt: all-en
    enc_sharing_group: [all]
    dec_sharing_group: [en1, ts, en2]
    node_gpu: 0:0
    path_src: /scratch/project_2005099/data/mammoth-hydra/wikilarge/en.src.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/wikilarge/en.tgt.sp
    transforms: [filtertoolong]
  translate_fr-en:
    src_tgt: all-en
    enc_sharing_group: [all]
    dec_sharing_group: [en1, mt, en2]
    node_gpu: 0:0
    path_src: /scratch/project_2005099/data/mammoth-hydra/unpc/UNv1.0.6way.fr.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/unpc/UNv1.0.6way.en.sp
    transforms: [filtertoolong]
  translate_ru-en:
    src_tgt: all-en
    enc_sharing_group: [all]
    dec_sharing_group: [en1, mt, en2]
    node_gpu: 0:0
    path_src: /scratch/project_2005099/data/mammoth-hydra/unpc/UNv1.0.6way.ru.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/unpc/UNv1.0.6way.en.sp
    transforms: [filtertoolong]

  # GPU 0:1
  defmod_fr:
    src_tgt: all-fr
    enc_sharing_group: [all]
    dec_sharing_group: [fr1, dm, fr2]
    node_gpu: 0:1
    path_src: /scratch/project_2005099/data/mammoth-hydra/codwoe/fr.src.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/codwoe/fr.tgt.sp
    transforms: [filtertoolong]
  pargen_fr:
    src_tgt: all-fr
    enc_sharing_group: [all]
    dec_sharing_group: [fr1, pg, fr2]
    node_gpu: 0:1
    path_src: /scratch/project_2005099/data/mammoth-hydra/tapaco/fr.src.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/tapaco/fr.tgt.sp
    transforms: [filtertoolong]
  texsim_fr:
    src_tgt: all-fr
    enc_sharing_group: [all]
    dec_sharing_group: [fr1, ts, fr2]
    node_gpu: 0:1
    path_src: /scratch/project_2005099/data/mammoth-hydra/wikilarge/fr.src.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/wikilarge/fr.tgt.sp
    transforms: [filtertoolong]
  translate_en-fr:
    src_tgt: all-fr
    enc_sharing_group: [all]
    dec_sharing_group: [fr1, mt, fr2]
    node_gpu: 0:1
    path_src: /scratch/project_2005099/data/mammoth-hydra/unpc/UNv1.0.6way.en.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/unpc/UNv1.0.6way.fr.sp
    transforms: [filtertoolong]
  translate_ru-fr:
    src_tgt: all-fr
    enc_sharing_group: [all]
    dec_sharing_group: [fr1, mt, fr2]
    node_gpu: 0:1
    path_src: /scratch/project_2005099/data/mammoth-hydra/unpc/UNv1.0.6way.ru.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/unpc/UNv1.0.6way.fr.sp
    transforms: [filtertoolong]

  # GPU 0:2
  defmod_ru:
    src_tgt: all-ru
    enc_sharing_group: [all]
    dec_sharing_group: [ru1, dm, ru2]
    node_gpu: 0:2
    path_src: /scratch/project_2005099/data/mammoth-hydra/codwoe/ru.src.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/codwoe/ru.tgt.sp
    transforms: [filtertoolong]
  pargen_ru:
    src_tgt: all-ru
    enc_sharing_group: [all]
    dec_sharing_group: [ru1, pg, ru2]
    node_gpu: 0:2
    path_src: /scratch/project_2005099/data/mammoth-hydra/tapaco/ru.src.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/tapaco/ru.tgt.sp
    transforms: [filtertoolong]
  texsim_ru:
    src_tgt: all-ru
    enc_sharing_group: [all]
    dec_sharing_group: [ru1, ts, ru2]
    node_gpu: 0:2
    path_src: /scratch/project_2005099/data/mammoth-hydra/ruadapt/ru.src.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/ruadapt/ru.tgt.sp
    transforms: [filtertoolong]
  translate_fr-ru:
    src_tgt: all-ru
    enc_sharing_group: [all]
    dec_sharing_group: [ru1, mt, ru2]
    node_gpu: 0:2
    path_src: /scratch/project_2005099/data/mammoth-hydra/unpc/UNv1.0.6way.fr.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/unpc/UNv1.0.6way.ru.sp
    transforms: [filtertoolong]
  translate_en-ru:
    src_tgt: all-ru
    enc_sharing_group: [all]
    dec_sharing_group: [ru1, mt, ru2]
    node_gpu: 0:1
    path_src: /scratch/project_2005099/data/mammoth-hydra/unpc/UNv1.0.6way.en.sp
    path_tgt: /scratch/project_2005099/data/mammoth-hydra/unpc/UNv1.0.6way.ru.sp
    transforms: [filtertoolong]

        
### Transform related opts:
#### Filter
src_seq_length: 200
tgt_seq_length: 200
#### Bart
src_subword_type: sentencepiece
tgt_subword_type: sentencepiece
mask_ratio: 0.2
replace_length: 1

batch_size: 4096
batch_type: tokens
normalization: tokens
valid_batch_size: 4096
max_generator_batches: 2
src_vocab_size: 100000
tgt_vocab_size: 100000
encoder_type: transformer
decoder_type: transformer
model_dim: 512
transformer_ff: 2048
heads: 8
enc_layers: [12]
dec_layers: [2, 2, 2]
dropout: 0.1
label_smoothing: 0.1
param_init: 0.0
param_init_glorot: true
position_encoding: true
valid_steps: 10000
warmup_steps: 10000
report_every: 100
save_checkpoint_steps: 10000
keep_checkpoint: -1
accum_count: 1
optim: adafactor
decay_method: none
learning_rate: 3.0
max_grad_norm: 0.0
seed: 3435
save_all_gpus: false

world_size: 3
gpu_ranks: [0, 1, 2]
node_rank: 0

src_subword_model: tools/demo/configs/hydra/vocab/mammoth-hydra.64k.spm.model
tgt_subword_model: tools/demo/configs/hydra/vocab/mammoth-hydra.64k.spm.model
