name: Lint & Tests

on: [push, pull_request]

jobs:
  lint-and-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8] # build only for 3.8 for now

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -e .
        pip install -r requirements.opt.txt
        pip install flake8==4.0.1
        pip install pytest==7.0.1 pytest-flake8==1.1.1
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 --max-line-length 120 .
    - name: Unit tests
      run: |
        python -m pytest
# ## Broken in FoTraNMT
#    - name: Test vocabulary build
#      run: |
#        python onmt/bin/build_vocab.py \
#          -config data/data.yaml \
#          -n_sample 5000 \
#          -src_vocab /tmp/onmt.vocab.src \
#          -tgt_vocab /tmp/onmt.vocab.tgt \
#          && rm -rf /tmp/sample
#    - name: Test vocabulary build with features
#      run: |
#        python onmt/bin/build_vocab.py \
#          -config data/features_data.yaml \
#          -src_vocab /tmp/onmt_feat.vocab.src \
#          -tgt_vocab /tmp/onmt_feat.vocab.tgt \
#          -src_feats_vocab '{"feat0": "/tmp/onmt_feat.vocab.feat0"}' \
#          -n_sample -1 \
#          && rm -rf /tmp/sample
